# Generated by Django 3.1.1 on 2020-09-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200910_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='locations_following',
            field=models.ManyToManyField(blank=True, related_name='locations_following', to='blog.Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='users_following',
            field=models.ManyToManyField(blank=True, related_name='following', to='blog.Profile'),
        ),
    ]
