# Generated by Django 3.1.1 on 2020-09-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200912_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='users_following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='blog.Profile'),
        ),
    ]
