# Generated by Django 3.1.1 on 2020-09-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200913_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
    ]
