# Generated by Django 3.1.1 on 2020-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='users_liked', through='blog.PostLike', to='blog.Post'),
        ),
    ]
